// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrjmknsQuturhqRavGdE1QSQ8HwqI5Q0s',
    appId: '1:751270723336:web:1d49444d665159a271f6bd',
    messagingSenderId: '751270723336',
    projectId: 'event-hub-92781',
    authDomain: 'event-hub-92781.firebaseapp.com',
    storageBucket: 'event-hub-92781.firebasestorage.app',
    measurementId: 'G-CBGZN6KFFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5-5J1T1yzF7HRKZ61ESKkD5YmtD8KV6A',
    appId: '1:751270723336:android:8877d8963c6240c671f6bd',
    messagingSenderId: '751270723336',
    projectId: 'event-hub-92781',
    storageBucket: 'event-hub-92781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxeptR-BIvo3n2zCgEgxl-qpgfcK7BZJo',
    appId: '1:751270723336:ios:18c39fbdc3ebe51671f6bd',
    messagingSenderId: '751270723336',
    projectId: 'event-hub-92781',
    storageBucket: 'event-hub-92781.firebasestorage.app',
    iosClientId: '751270723336-k6vl3oll8knl0lr26uvtj5cauo3n975v.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxeptR-BIvo3n2zCgEgxl-qpgfcK7BZJo',
    appId: '1:751270723336:ios:18c39fbdc3ebe51671f6bd',
    messagingSenderId: '751270723336',
    projectId: 'event-hub-92781',
    storageBucket: 'event-hub-92781.firebasestorage.app',
    iosClientId: '751270723336-k6vl3oll8knl0lr26uvtj5cauo3n975v.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrjmknsQuturhqRavGdE1QSQ8HwqI5Q0s',
    appId: '1:751270723336:web:f341eb94319d662771f6bd',
    messagingSenderId: '751270723336',
    projectId: 'event-hub-92781',
    authDomain: 'event-hub-92781.firebaseapp.com',
    storageBucket: 'event-hub-92781.firebasestorage.app',
    measurementId: 'G-4Z3S61HMDF',
  );
}
